name: build cpp

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build_matrix:
    strategy:
      matrix:
        os: [ubuntu-latest,windows-latest,macos-latest]
    runs-on: ${{ matrix.os }}
    env:
      app_name: hi_${{ matrix.os }}.o
    steps:
      - name: print matrix env
        run: "echo os: ${{ matrix.os }}"
        
      - uses: actions/checkout@v3
      - name: build 
        run: g++ hello.cpp -o ${{ env.app_name }}

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: cpp_app_matrix
          path: ${{ env.app_name }}
          retention-days: 5
