# This is a basic workflow to help you get started with Actions

name: build cpp

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_cpp:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: ls
        run: ls -la
        
      - uses: actions/checkout@v3
      
      - name: env report
        run: |
          ls -la
          printenv
          
      - name: build 
        run: |
          g++ hello.cpp -o hello.o
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: cpp_app
          path: hello.o
          retention-days: 5
          
